-- Script SQL para configurar o banco Oracle
-- Execute como DBA (usuário com privilégios administrativos)

-- 1. Criar as tabelas (baseado no DER)
CREATE TABLE CONTACORRENTE (
    IDCONTACORRENTE NUMBER PRIMARY KEY,
    NUMERO VARCHAR2(20) UNIQUE NOT NULL,
    CPF NUMBER(11) NOT NULL,
    ATIVO NUMBER(1) DEFAULT 1 CHECK (ATIVO IN (0,1)),
    SENHA VARCHAR2(255) NOT NULL,
    SALDO NUMBER(15,2) NOT NULL
);

CREATE TABLE MOVIMENTO (
    IDMOVIMENTO NUMBER PRIMARY KEY,
    IDCONTACORRENTE NUMBER NOT NULL,
    DATAMOVIMENTO DATE DEFAULT SYSDATE,
    TIPOMOVIMENTO VARCHAR2(30) NOT NULL CHECK (TIPOMOVIMENTO IN ('C', 'D')),
    VALOR NUMBER(15,2) NOT NULL CHECK (VALOR > 0),
    CONSTRAINT FK_MOVIMENTO_CONTA FOREIGN KEY (IDCONTACORRENTE) REFERENCES CONTACORRENTE(IDCONTACORRENTE)
);

CREATE TABLE IDEMPOTENCIA (
    CHAVE_IDEMPOTENCIA VARCHAR2(100) PRIMARY KEY,
    REQUISICAO CLOB NOT NULL,
    RESULTADO CLOB NOT NULL,
    DATA_CRIACAO DATE DEFAULT SYSDATE
);

-- 2. Criar as sequences necessárias
CREATE SEQUENCE CONTACORRENTE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE MOVIMENTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 3. Criar índices para melhorar performance
CREATE INDEX IDX_MOVIMENTO_CONTA ON MOVIMENTO(IDCONTACORRENTE);
CREATE INDEX IDX_MOVIMENTO_DATA ON MOVIMENTO(DATAMOVIMENTO);

COMMIT;

