-- Script SQL para configurar o banco Oracle
-- Execute como DBA (usuário com privilégios administrativos)

-- 1. Criar as tabelas (baseado no DER)

CREATE TABLE TRANSFERENCIA (
    IDTRANSFERENCIA NUMBER PRIMARY KEY,
    IDCONTACORRENTE_ORIGEM NUMBER NOT NULL,
    IDCONTACORRENTE_DESTINO NUMBER NOT NULL,
    DATAMOVIMENTO DATE DEFAULT SYSDATE,
    VALOR NUMBER(15,2) NOT NULL CHECK (VALOR > 0)
);

CREATE TABLE IDEMPOTENCIA (
    CHAVE_IDEMPOTENCIA VARCHAR2(100) PRIMARY KEY,
    REQUISICAO CLOB NOT NULL,
    RESULTADO CLOB NOT NULL,
    DATA_CRIACAO DATE DEFAULT SYSDATE
);

-- 2. Criar as sequences necessárias
CREATE SEQUENCE TRANSFERENCIA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 3. Criar índices para melhorar performance
CREATE INDEX IDX_TRANSFERENCIA_ORIGEM ON TRANSFERENCIA(IDCONTACORRENTE_ORIGEM);
CREATE INDEX IDX_TRANSFERENCIA_DESTINO ON TRANSFERENCIA(IDCONTACORRENTE_DESTINO);
CREATE INDEX IDX_TRANSFERENCIA_DATA ON TRANSFERENCIA(DATAMOVIMENTO);

COMMIT;

